/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_warung_podomoro;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdurraihan
 */
public class adminpage extends javax.swing.JFrame {

   Profile P;
   static DefaultTableModel m, n;
   
    public adminpage() {
        initComponents();
        settingTable();        
        viewData("");
    }
    
    public adminpage(Profile p) {
        initComponents();
        this.P = p;
        
        jLabel2.setText(P.getFullname() + "," + P.getLevel());
        settingTable();
        viewData("");
        viewDataProduk("");
        
        
        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtkey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatauser = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btntambahproduk = new javax.swing.JButton();
        btnubahproduk = new javax.swing.JButton();
        btnhapusproduk = new javax.swing.JButton();
        btnrefreshproduk = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcariproduk = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldataproduk = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btntambah.setBackground(new java.awt.Color(0, 153, 255));
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(0, 153, 255));
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_warung_podomoro/search.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 37, -1));

        txtkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeyActionPerformed(evt);
            }
        });
        txtkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkeyKeyReleased(evt);
            }
        });
        jPanel5.add(txtkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 7, 232, 30));

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(btnubah)
                            .addComponent(btnhapus)
                            .addComponent(btnrefresh)
                            .addComponent(jButton1))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbldatauser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO", "ID", "NAMA LENGKAP", "USERNAME", "PASSWORD", "LEVEL"
            }
        ));
        jScrollPane1.setViewportView(tbldatauser);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Data User", jPanel2);

        jPanel9.setLayout(new java.awt.BorderLayout());

        btntambahproduk.setBackground(new java.awt.Color(0, 153, 255));
        btntambahproduk.setText("Tambah");
        btntambahproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahprodukActionPerformed(evt);
            }
        });

        btnubahproduk.setBackground(new java.awt.Color(0, 153, 255));
        btnubahproduk.setText("ubah");
        btnubahproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahprodukActionPerformed(evt);
            }
        });

        btnhapusproduk.setBackground(new java.awt.Color(255, 51, 51));
        btnhapusproduk.setText("Hapus");
        btnhapusproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusprodukActionPerformed(evt);
            }
        });

        btnrefreshproduk.setText("Refresh");
        btnrefreshproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshprodukActionPerformed(evt);
            }
        });

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_warung_podomoro/search.png"))); // NOI18N
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 16, 30, -1));

        txtcariproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariprodukActionPerformed(evt);
            }
        });
        txtcariproduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariprodukKeyReleased(evt);
            }
        });
        jPanel11.add(txtcariproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 30));

        jButton2.setText("logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntambahproduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnubahproduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapusproduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrefreshproduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambahproduk)
                            .addComponent(btnubahproduk)
                            .addComponent(btnhapusproduk)
                            .addComponent(btnrefreshproduk)
                            .addComponent(jButton2)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));

        tbldataproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "ID", "KODE PRODUK", "NAMA PRODUK", "GAMBAR", "KATEGORI", "SUPPLIER", "HARGA JUAL", "HARGA BELI", "STOK"
            }
        ));
        jScrollPane2.setViewportView(tbldataproduk);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(666, 666, 666)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data produk", jPanel8);

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PODOMORO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel13))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTabbedPane1))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int n = tbldatauser.getSelectedRow();
        if (n != -1) {
            int id = Integer.parseInt(tbldatauser.getValueAt(n, 1).toString());
            String fullname = tbldatauser.getValueAt(n, 2).toString();
             
            int opsi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda Yakin Ingin Menghapus Data " + fullname+"?",
                    "Hapus Data",
                    JOptionPane.YES_NO_OPTION);
             
            if (opsi == 0) {
                 String Q = "DELETE FROM tb_user "
                         + "WHERE id_user= " + id;
                 
                 try {
                     Connection K = Koneksi2.Go();
                     Statement S = K.createStatement();
                     S.executeUpdate(Q);
                     viewData("");
                     JOptionPane.showMessageDialog(this, "Data "+ fullname + " Telah Dihapus");
                 }catch(HeadlessException | SQLException e){
                     e.printStackTrace();
                 }   
            }
        }else{
            JOptionPane.showMessageDialog(this, "anda Belum Memilih Data");
    }//GEN-LAST:event_btnhapusActionPerformed
    }
    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        tambahdata T = new tambahdata(this, true);
        T.setVisible(true); 
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        int n = tbldatauser.getSelectedRow();
        if (n != -1) {
            int id = Integer.parseInt(tbldatauser.getValueAt(n, 1).toString());
            String fullname = tbldatauser.getValueAt(n,2).toString();
            String username = tbldatauser.getValueAt(n, 3).toString();
            String password =  tbldatauser.getValueAt(n, 4).toString();
            String level = tbldatauser.getValueAt(n, 5).toString();
            UbahData U = new UbahData(this, true);
            U.setId_user(id);
            U.setFullname(fullname);
            U.setUsername(username);
            U.setPassword(password);
            U.setLevel(level);
            U.setVisible(true);
             
        }else{
            JOptionPane.showMessageDialog(this, "Anda Belum Memilih Data");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void txtkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeyKeyReleased
        // TODO add your handling code here:
        String key = txtkey.getText().trim(); // Trim untuk menghapus spasi di awal/akhir
if (!key.isEmpty()) {
    viewData(key);
} else {
    viewData(""); // Jika key kosong, tampilkan semua data
}

    }//GEN-LAST:event_txtkeyKeyReleased

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        viewData("");
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void txtkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkeyActionPerformed

    private void txtcariprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariprodukActionPerformed

    private void btnubahprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahprodukActionPerformed
        int n = tbldataproduk.getSelectedRow();
        if(n != -1){
            ubahdataproduk U = null;
            try {
                U = new ubahdataproduk(this, true);
            } catch (SQLException ex) {
                Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
            }
            U.setId(Integer.parseInt(tbldataproduk.getValueAt(n, 1).toString()));
            U.setKode(tbldataproduk.getValueAt(n, 2).toString());
            U.setNama(tbldataproduk.getValueAt(n, 3).toString());
            U.setGambar(tbldataproduk.getValueAt(n, 4).toString());
            U.setKategori(tbldataproduk.getValueAt(n, 5).toString());
            U.setSupplier(tbldataproduk.getValueAt(n, 6).toString());
            U.setHargaJual(Double.parseDouble(tbldataproduk.getValueAt(n, 7).toString()));
            U.setHargaBeli(Double.parseDouble(tbldataproduk.getValueAt(n, 8).toString()));
            U.setStok(Integer.parseInt(tbldataproduk.getValueAt(n, 9).toString()));
            U.setVisible(true); 
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnubahprodukActionPerformed

    private void btnrefreshprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshprodukActionPerformed
        // TODO add your handling code here:
        viewDataProduk("");
    }//GEN-LAST:event_btnrefreshprodukActionPerformed

    private void txtcariprodukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariprodukKeyReleased
        String key = txtcariproduk.getText().trim();
        if (!key.isEmpty()) {
            viewDataProduk(key);
        }else{
            viewDataProduk("");
        }
    }//GEN-LAST:event_txtcariprodukKeyReleased

    private void btnhapusprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusprodukActionPerformed
        // TODO add your handling code here:
        int n = tbldataproduk.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tbldataproduk.getValueAt(n, 1).toString());
            String kode = tbldataproduk.getValueAt(n, 2).toString() + " - " + tbldataproduk.getValueAt(n, 3).toString();
            
            int opsi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin menghapus data "+kode+"?", 
                    "Hapus Data", 
                    JOptionPane.YES_NO_OPTION);
            if(opsi == 0){
                String Q = "DELETE FROM produk "
                        + "WHERE id="+id;
                
                try {
                    Connection K = Koneksi2.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewDataProduk(""); 
                    JOptionPane.showMessageDialog(this, "Data "+kode+" telah terhapus");
                } catch (SQLException e) {
                }
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btnhapusprodukActionPerformed

    private void btntambahprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahprodukActionPerformed
        // TODO add your handling code here:
        tambahproduk T = null;
       try {
           T = new tambahproduk(this, rootPaneCheckingEnabled);
       } catch (SQLException ex) {
           Logger.getLogger(adminpage.class.getName()).log(Level.SEVERE, null, ex);
       }
        T.setVisible(true);
    }//GEN-LAST:event_btntambahprodukActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loginyoba L = new loginyoba();
        L.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginyoba L = new loginyoba();
        L.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapusproduk;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnrefreshproduk;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntambahproduk;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton btnubahproduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbldataproduk;
    private javax.swing.JTable tbldatauser;
    private javax.swing.JTextField txtcariproduk;
    private javax.swing.JTextField txtkey;
    // End of variables declaration//GEN-END:variables

public static void viewData(String where) {
        try {
            //kode kita
            for (int i = m.getRowCount()-1; i >=0; i--) {
                m.removeRow(i);
            }

            Connection K = Koneksi2.Go();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM tb_user WHERE " +
                       "fullname LIKE '%" + where + "%' OR " +
                       "username LIKE '%" + where + "%' OR " +
                       "password LIKE '%" + where + "%' OR " +
                       "level_id LIKE '%" + where + "%'";
//            System.out.println(Q);
            ResultSet R = S.executeQuery(Q);
            int no = 1;
            while (R.next()) {
                int id = R.getInt("id_user");
                String fullname = R.getString("fullname");
                String username = R.getString("username");
                String password = R.getString("password");
                String level = R.getString("level_id");

                Object[] D = {no, id, fullname, username, password, level};
                m.addRow(D);

                no++;
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
    }

    public static void viewDataProduk(String where) {
        try {
            for (int i = n.getRowCount()-1; i >=0; i--){
                n.removeRow(i);
            }
            
            Connection K = Koneksi2.Go();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM produk WHERE "
                + "kode LIKE '%" + where + "%' OR "
                + "nama LIKE '%" + where + "%' OR "
                + "kategori LIKE '%" + where + "%' OR "
                + "supplier LIKE '%" + where + "%' OR "
                + "harga_jual LIKE '%" + where + "%' OR "
                + "harga_beli LIKE '%" + where + "%'";
            ResultSet R = S.executeQuery(Q);
            int no = 1;
            while (R.next()){
                int id = R.getInt("id");
                String kode = R.getString("kode");
                String nama = R.getString("nama");
                String gambar = R.getString("gambar");
                String kategori = R.getString("kategori");
                String suplier = R.getString("supplier");
                int harga_jual = R.getInt("harga_jual");
                int harga_beli = R.getInt("harga_beli");
                int stok = R.getInt("stok");
                
                Object[] D = {no, id, kode, nama, gambar, kategori, suplier, harga_jual, harga_beli, stok};
                n.addRow(D);
                
                no++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
        private void settingTable(){
           m = (DefaultTableModel) tbldatauser.getModel();
           tbldatauser.getColumnModel().getColumn(0).setMinWidth(50);
           tbldatauser.getColumnModel().getColumn(0).setMaxWidth(70);
           
           tbldatauser.getColumnModel().getColumn(1).setMinWidth(0);
           tbldatauser.getColumnModel().getColumn(1).setMaxWidth(0);
           
           tbldatauser.getColumnModel().getColumn(2).setMinWidth(350);
           tbldatauser.getColumnModel().getColumn(2).setMaxWidth(350);
           
           n = (DefaultTableModel) tbldataproduk.getModel();
           tbldataproduk.getColumnModel().getColumn(0).setMinWidth(50);
           tbldataproduk.getColumnModel().getColumn(0).setMaxWidth(70);
           
           tbldataproduk.getColumnModel().getColumn(1).setMinWidth(0);
           tbldataproduk.getColumnModel().getColumn(1).setMaxWidth(0);

           }
}


