/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_warung_podomoro;

/**
 *
 * @author abdurraihan
 */
public class ownerpage extends javax.swing.JFrame {

    /**
     * Creates new form ownerpage
     */
    public ownerpage() {
        initComponents();
    }

    ownerpage(Profile P) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpmenu = new javax.swing.JPanel();
        JBTNPROFIL = new javax.swing.JButton();
        JBTNMENU = new javax.swing.JButton();
        JBTNTRANSAKSI = new javax.swing.JButton();
        JBTNKELUAR = new javax.swing.JButton();
        jpheader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jpisi = new javax.swing.JPanel();
        jpprofil = new javax.swing.JPanel();
        jbprofil = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        jbmenu = new javax.swing.JLabel();
        jptransaksi = new javax.swing.JPanel();
        jbtransaksi = new javax.swing.JLabel();
        jplogout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpmenu.setBackground(new java.awt.Color(153, 153, 153));

        JBTNPROFIL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_warung_podomoro/user.png"))); // NOI18N
        JBTNPROFIL.setText("profil");
        JBTNPROFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNPROFILActionPerformed(evt);
            }
        });

        JBTNMENU.setIcon(new javax.swing.ImageIcon("C:\\Users\\abdurraihan\\Downloads\\menu.png")); // NOI18N
        JBTNMENU.setText("menu");
        JBTNMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNMENUActionPerformed(evt);
            }
        });

        JBTNTRANSAKSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_warung_podomoro/transaction.png"))); // NOI18N
        JBTNTRANSAKSI.setText("transaksi");
        JBTNTRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNTRANSAKSIActionPerformed(evt);
            }
        });

        JBTNKELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_warung_podomoro/logout.png"))); // NOI18N
        JBTNKELUAR.setText("keluar");
        JBTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNKELUARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpmenuLayout = new javax.swing.GroupLayout(jpmenu);
        jpmenu.setLayout(jpmenuLayout);
        jpmenuLayout.setHorizontalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpmenuLayout.createSequentialGroup()
                        .addComponent(JBTNPROFIL, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JBTNKELUAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTNTRANSAKSI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTNMENU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jpmenuLayout.setVerticalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JBTNPROFIL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(JBTNMENU)
                .addGap(18, 18, 18)
                .addComponent(JBTNTRANSAKSI)
                .addGap(18, 18, 18)
                .addComponent(JBTNKELUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jpheader.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abdurraihan\\Downloads\\user.png")); // NOI18N

        lbllogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\abdurraihan\\Downloads\\logout.png")); // NOI18N
        lbllogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbllogoutKeyPressed(evt);
            }
        });

        jLabel3.setText("owner");

        jLabel12.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jLabel12.setText("PODOMORO");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\abdurraihan\\Downloads\\chef (1).png")); // NOI18N

        javax.swing.GroupLayout jpheaderLayout = new javax.swing.GroupLayout(jpheader);
        jpheader.setLayout(jpheaderLayout);
        jpheaderLayout.setHorizontalGroup(
            jpheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpheaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpheaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbllogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpheaderLayout.setVerticalGroup(
            jpheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpheaderLayout.createSequentialGroup()
                .addGroup(jpheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpheaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbllogout)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jpisi.setBackground(new java.awt.Color(204, 255, 204));
        jpisi.setForeground(new java.awt.Color(204, 255, 204));

        jpprofil.setBackground(new java.awt.Color(204, 204, 255));

        jbprofil.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jbprofil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbprofil.setText("PROFIL");

        javax.swing.GroupLayout jpprofilLayout = new javax.swing.GroupLayout(jpprofil);
        jpprofil.setLayout(jpprofilLayout);
        jpprofilLayout.setHorizontalGroup(
            jpprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpprofilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbprofil, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpprofilLayout.setVerticalGroup(
            jpprofilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpprofilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbprofil)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jpMenu.setBackground(new java.awt.Color(255, 255, 153));

        jbmenu.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jbmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbmenu.setText("MENU");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbmenu)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jptransaksi.setBackground(new java.awt.Color(255, 204, 204));

        jbtransaksi.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jbtransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtransaksi.setText("TRANSAKSI");

        javax.swing.GroupLayout jptransaksiLayout = new javax.swing.GroupLayout(jptransaksi);
        jptransaksi.setLayout(jptransaksiLayout);
        jptransaksiLayout.setHorizontalGroup(
            jptransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jptransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jptransaksiLayout.setVerticalGroup(
            jptransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jptransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtransaksi)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jplogout.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jplogoutLayout = new javax.swing.GroupLayout(jplogout);
        jplogout.setLayout(jplogoutLayout);
        jplogoutLayout.setHorizontalGroup(
            jplogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jplogoutLayout.setVerticalGroup(
            jplogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpisiLayout = new javax.swing.GroupLayout(jpisi);
        jpisi.setLayout(jpisiLayout);
        jpisiLayout.setHorizontalGroup(
            jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpprofil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jptransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jplogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpisiLayout.setVerticalGroup(
            jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpprofil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jptransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpisiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jplogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbllogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbllogoutKeyPressed

    }//GEN-LAST:event_lbllogoutKeyPressed

    private void JBTNTRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNTRANSAKSIActionPerformed
        // TODO add your handling code here:
        jptransaksi.removeAll();
        jptransaksi.repaint();
        jptransaksi.revalidate();
        
        //menambahkan panel 
        
        jptransaksi.add(jptransaksi);
        jptransaksi.repaint();
        jptransaksi.revalidate();
        
    }//GEN-LAST:event_JBTNTRANSAKSIActionPerformed

    private void JBTNPROFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNPROFILActionPerformed
        // TODO add your handling code here:
        jpisi.removeAll();
        jpisi.repaint();
        jpisi.revalidate();
        
        //menambahkan panel 
        
        jpisi.add(jpprofil);
        jpisi.repaint();
        jpisi.revalidate();
        
    }//GEN-LAST:event_JBTNPROFILActionPerformed

    private void JBTNMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNMENUActionPerformed
        // TODO add your handling code here:
        jpMenu.removeAll();
        jpMenu.repaint();
        jpmenu.revalidate();
        
        //menambahkan panel 
        
        jpMenu.add(jpMenu);
        jpMenu.repaint();
        jpMenu.revalidate();
    }//GEN-LAST:event_JBTNMENUActionPerformed

    private void JBTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNKELUARActionPerformed
        // TODO add your handling code here:
        jplogout.removeAll();
        jplogout.repaint();
        jplogout.revalidate();
        
        //menambahkan panel 
        
        jplogout.add(jplogout);
        jplogout.repaint();
        jplogout.revalidate();
        
    }//GEN-LAST:event_JBTNKELUARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNKELUAR;
    private javax.swing.JButton JBTNMENU;
    private javax.swing.JButton JBTNPROFIL;
    private javax.swing.JButton JBTNTRANSAKSI;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbmenu;
    private javax.swing.JLabel jbprofil;
    private javax.swing.JLabel jbtransaksi;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpheader;
    private javax.swing.JPanel jpisi;
    private javax.swing.JPanel jplogout;
    private javax.swing.JPanel jpmenu;
    private javax.swing.JPanel jpprofil;
    private javax.swing.JPanel jptransaksi;
    private javax.swing.JLabel lbllogout;
    // End of variables declaration//GEN-END:variables
}
